inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and
