inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
